### ISSUE TITLE
Typo in check_crs

### ISSUE THREAD

**Issue by dfifield** [densitymodelling/dsmextra#12]
There's a spelling error at line 263 of utils.R:

`  }else{supressWarnings(coordinate.system <- sp::CRS(coordinate.system))}`

where "supressWarnings" is missing the second "p".

Thanks so much!
Dave

**Comment by pjbouchet** [comment]
Thank you Dave! This has now been corrected.
Best, Phil

**Comment by dfifield** [comment]
Thanks Phil!

Dave



Sent from my Bell Samsung device over Canada's largest network.



-------- Original message --------
From: Phil Bouchet ***@***.***>
Date: 2022-02-08 10:44 a.m. (GMT-03:30)
To: densitymodelling/dsmextra ***@***.***>
Cc: Dave Fifield ***@***.***>, Author ***@***.***>
Subject: Re: [densitymodelling/dsmextra] Typo in check_crs (Issue #12)


Thank you Dave! This has now been corrected.
Best, Phil
