### ISSUE TITLE
Package dependency issue

### ISSUE THREAD

**Issue by lindesaysh** [densitymodelling/dsmextra#6]
Hi Phil,

Len suggested looking at your cool new package for checking extrapolation.  Unfortunately I have stumbled at the first hurdle.  The packages WhatIf and Zelig were removed from CRAN on the 7th and 23rd March.  I have found the archive versions and installed those but they need a whole sweep of dependencies. 

For info Zelig needed the following packages and had to be installed prior to WhatIf: 
install.packages(c("AER", "Amelia", "coda", "Formula", "geepack", "MatchIt", "maxLik", "MCMCpack", "survey", "VGAM"))

WhatIf required:
install.packages(c("lpSolve", "pbmcapply"))

Also, I'm using 
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

I'm up and running now though so can start to play.

Cheers,
Lindesay
(CREEM)

**Comment by pjbouchet** [comment]
Hi Lindesay,

Thanks for bringing this to our attention. This has now been addressed in **version 1.1.0**, and dsmextra should automatically pull both WhatIf and Zelig directly from their Github repositories during installation. If any issues still occur, both packages can be installed manually with the following commands:

`if (!require("remotes")) install.packages("remotes")`
`remotes::install_github("IQSS/Zelig")`
`remotes::install_github("IQSS/WhatIf")`

Best, Phil
