### ISSUE TITLE
compare_covariates, param requiring update

### ISSUE THREAD

**Issue by FGrossmann** [densitymodelling/dsmextra#8]
Function: compare_covariates

@param extrapolation.type Character string. Type of extrapolation to be assessed. Can be one of \code{univariate}, \code{combinatorial}, or \code{both} (default).

Shouldn't this read:
 **"multivariate"**  rather than combinatorial, as per lines 71-72

  if(!extrapolation.type%in%c("both", "univariate", "multivariate"))
    stop("Unknown extrapolation type")

**Comment by pjbouchet** [comment]
Good pick up! This has now been corrected by replacing "multivariate" with "combinatorial", for consistency with the terminology used throughout the rest of the package.

`if(!extrapolation.type%in%c("both", "univariate", "combinatorial"))`
`stop("Unknown extrapolation type")`
